# Generated by Django 2.1.7 on 2019-03-13 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecn_id', models.IntegerField(default=1, null=True, verbose_name='کد متخصص')),
                ('create_date', models.DateField(null=True, verbose_name='تاریخ ایجاد')),
                ('ref', models.IntegerField(default=0, null=True, verbose_name='ارجاع')),
                ('owner', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('qa_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='support.QA', verbose_name='شماره سئوال')),
                ('user_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='support.Pepole', verbose_name='کد کاربر')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت',
            },
        ),
    ]
